name: dartboy
description: Multiplatform Gameboy Color emulator using dart and flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <=2.15.1"

dependencies:
  flutter:
    sdk: flutter
  wave_generator: ^0.1.0
  audioplayers: ^0.20.1
  file_picker: ^4.2.8
  image: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
